### ISSUE TITLE
Error: Command failed: Individual stylesheets must be in the sass directory.

### ISSUE THREAD

**Issue by Zuur** [quaertym/ember-cli-compass-compiler#26]
When building from a directory path *with a space in*, using Ember 0.0.46 I get the following error:

```
C:\my\path\with\a\s p a c e\in\it>ember serve
version: 0.0.46
Livereload server on port 35729
Serving on http://0.0.0.0:4200
Individual stylesheets must be in the sass directory.


Command failed: Individual stylesheets must be in the sass directory.

Error: Command failed: Individual stylesheets must be in the sass directory.

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

The command being executed is:
```
compass compile --sass-dir=app/styles --css-dir=C:\my\path\with\a\s p a c e\in\it\tmp\compass_compiler-tmp_cache_dir-nMCB2moN.tmp\assets --output-style
=compressed
```

If I wrap the ```--css-dir``` value in quotes (by hard-coding it) it will fix the problem, but I can't see an easy way to easily do that dynamically.

**Comment by Glavin001** [comment]
I am experiencing this bug again. I do have a space in my parent directory.

**Comment by quaertym** [comment]
Does this fix the issue?
```
var app = new EmberApp({
  compassOptions: {
    getCssDir: function(outputDir) {
      return '"'+path.join(outputDir, outputPath)+'"';
    }
  }
});
```

**Comment by Glavin001** [comment]
I've narrowed it down the dependency tree to https://github.com/quaertym/compass-compile/blob/master/lib/compass.js#L9-L10 

I think the problem is with [`dargs`](https://github.com/sindresorhus/dargs) not escaping strings with spaces when creating the arguments.

**Comment by Glavin001** [comment]
@quaertym yup changing https://github.com/quaertym/ember-cli-compass-compiler/blob/master/index.js#L30 to `return '"'+path.join(outputDir, outputPath)+'"';` fixes the problem.

**Comment by quaertym** [comment]
@Glavin001 :+1: , I will publish the fix as soon as possible.

**Comment by Glavin001** [comment]
@quaertym I submitted a little Pull Request. :smile:

**Comment by mhenley-uk** [comment]
Is there a planned release date that includes this new fix? Cheers in advance!

**Comment by quaertym** [comment]
@mhenley-uk It released in https://github.com/quaertym/ember-cli-compass-compiler/releases/tag/v0.3.1

**Comment by mhenley-uk** [comment]
@quaertym Thanks
