### ISSUE TITLE
Use app.scss, not [appname]

### ISSUE THREAD

**Issue by samselikoff** [quaertym/ember-cli-compass-compiler#35]
app.scss is the ember-cli convention, and also the convention other libs use (e.g. ember-cli-bootstrap-sass). The sass import paths get screwed up when we switch to [appname].

We should probably use app.scss.

**Comment by mkalita** [comment]
INCYDK
```
$ ember new zzz
version: 0.2.0-beta.1
installing
(...)
  create app/styles/app.css
(...)
```

**Comment by FlouksBerlin** [comment]
On my end, since I'm using ember-cli-compass-compiler, I always get `dist/assets/app.css`.
But actually ember-cli expects `dist/assets/<app-name.css>`, like @quaertym already said.

Is there a way to set a name for the output-css-file in the compassOptions?

**Comment by sunocean-sand** [comment]
Is this solved by generating app.scss in addition to [appname].css that's already there?

I'm encountering this problem while installing the ember-cli-cordova addon.

**Comment by quaertym** [comment]
Fixed by https://github.com/quaertym/ember-cli-compass-compiler/commit/22e27ee058cde46af0fca258bb61fcb9076d719b.
