### ISSUE TITLE
Blows up if project path has spaces

### ISSUE THREAD

**Issue by jamesarosen** [quaertym/ember-cli-compass-compiler#39]
If I'm working in an Ember project whose path is `/home/me/My Project/`, running `ember build` results in `Build failed. Command failed: Individual stylesheets must be in the sass directory.`

I added some debugging info to `compass.js`, emitting the `command` at the end of `generateCommand`. It emits `compass compile --sass-dir=app/styles --css-dir=/home/meMy Project/tmp/compass_compiler-tmp_cache_dir-GH0EYW48.tmp/assets --output-style=compressed`. All paths should be quoted.

http://stackoverflow.com/questions/1779858/how-do-i-escape-a-string-for-a-shell-command-in-nodejs-v8-javascript-engine suggests using `createChildProcess` instead of `exec`, though that API is somewhat cumbersome. https://blog.liftsecurity.io/2014/08/19/Avoid-Command-Injection-Node.js suggests `require('child_process').spawn`, which accepts an Array of additional arguments, though that API is about as bad.

http://stackoverflow.com/questions/16395612/unable-to-execute-child-process-exec-when-path-has-spaces offers a simpler fix, though it's less robust. Simply run `.replace(/ /g, "\\ ")` on `cssDir` or `sassDir`.

**Comment by jamesarosen** [comment]
The simple patch works fine for my case:
```js
Compass.prototype.compile = function(srcDir, destDir, options) {
  var cssDir  = path.join(destDir, 'assets');

  merge(options, {
    cssDir: cssDir
  });

  options.cssDir = options.cssDir.replace(/ /g, '\\ ');
  options.sassDir = options.sassDir.replace(/ /g, '\\ ');

  var command = this.generateCommand(options);
  ...
};
```

**Comment by quaertym** [comment]
@jamesarosen which version do you use?

**Comment by jamesarosen** [comment]
This is on 0.0.17. 0.0.18 [fixes the problem](https://github.com/quaertym/ember-cli-compass-compiler/blob/7b0c513f0ba1fa1254549dc9d9ef57ae874611e5/compass.js#L24) for `cssDir`, but I don't see a fix for `sassDir`.

**Comment by jamesarosen** [comment]
(Still, 0.0.18 works for me since it's my *project* directory that has the space and `sassDir` is relative to that, not absolute.)

**Comment by quaertym** [comment]
Please close if it is not an issue anymore.

**Comment by jamesarosen** [comment]
If someone set `sassDir: "app/custom styles"` then they'd see the same problem. I think that's pretty unlikely, though. I'll close for now.
