### ISSUE TITLE
Importing from vendor

### ISSUE THREAD

**Issue by ofridagan** [quaertym/ember-cli-compass-compiler#40]
In Ember-Cli docs it says:
The vendor trees that are provided upon instantiation are available to your dynamic style files. Take the following example (in app/styles/app.scss):
@import "bower_components/foundation/scss/normalize.scss";

This works when using broccoli-sass, but I couldn't get it to work with ember-cli-compass-compiler.

Is it possible? What do I need to do?

Thanks!

**Comment by quaertym** [comment]
You should import the necessary file from your `appname.scss`. For example for bootstrap sass I do the following:
```
@import "../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
```

**Comment by ofridagan** [comment]
Oh.. I was using app.sass
I wonder why the compilation even worked without the vendor imports...
Would be nice to have an error about that on the console, or at least document this (did I miss it?)

Anyway, it works now. Thanks!!
