### ISSUE TITLE
Doesn't follow outputsPath

### ISSUE THREAD

**Issue by trev** [quaertym/ember-cli-compass-compiler#42]
I've got something like this in my Brocfile.js:

```js
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'app': '/stuff/dyo.css'
      },
      js: '/stuff/dyo.js'
    },
    vendor: {
      css: '/stuff/vendor.css',
      js: '/stuff/vendor.js'
    }
  }
});
```

Everything BUT the app.css will build into `dist/stuff`. The app.css still goes to `dist/assets`.

**Comment by markhorgan** [comment]
I had the same problem. "assets" is hard-coded in the npm. A hack is to change the js file:

node_modules/ember-cli-compass-compiler/compass.js:
```
Compass.prototype.compile = function(srcDir, destDir, options) {
  var cssDir  = path.join(destDir, 'stuff');
```

**Comment by marlonmarcello** [comment]
Same happening here.

**Comment by quaertym** [comment]
`outputPaths` are supported beginning from `0.2.0` release.
