### ISSUE TITLE
Can't find app.scss

### ISSUE THREAD

**Issue by Marthyn** [quaertym/ember-cli-compass-compiler#46]
Since upgrading to ember cli 0.2.0 beta 1 i get this error

```
<myappname>/tmp/compass_compiler-tmp_dest_dir-OGIul1BP.tmp/app/styles/app.[scss|sass] does not exist
```

When i look in finder i find this:

![screen shot 2015-02-26 at 17 38 45 1](https://cloud.githubusercontent.com/assets/642544/6396379/61dc222c-bdde-11e4-97f7-ae64be190742.png)

How can i fix this?

**Comment by mkalita** [comment]
Have you seen this #35? I had similar problem, but in my case removing all broccoli-... from package.json (except broccoli-asset-rev) helped, also had to remove custom "broccoli" stuff from Brocfile.js of course.

**Comment by Marthyn** [comment]
It was indeed removing all the broccoli stuff, thanks!

**Comment by sunocean-sand** [comment]
@mkalita  did you remove
```var EmberApp = require('ember-cli/lib/broccoli/ember-app');```

It seems important that all my bootstrap depends on the imported ember-app in the broccoli file?
