### ISSUE TITLE
I need a how-to tutorial

### ISSUE THREAD

**Issue by mooror** [quaertym/ember-cli-compass-compiler#48]
Can someone do up a quick how-to guide/tut? I cannot seem to get this ember-cli plugin working but It seem to be the only pluggin for ember-cli that supports ruby gem imports to scss. I am getting this error: 
```
C:\Windows\system32\cmd.exe /s /c "compass compile --sass-dir=app/styles --css-dir='E:\Profile\*myEmberPath*\tmp\compass_compiler-tmp_cache_dir-iNNlyW42.tmp\assets' --output-style=compressed"  
```
I haven't placed anything in the broccfile for options so this is just what I'm getting by default. I have also made sure to remove broccoli-sass. Any help will be greatly appreciated.

**Comment by mooror** [comment]
Update: I was able to get this error to go away but only after removing all the other folders and removing all the content in my appname.scss. The strange thing is that I don't get an error in compiling until I try to include susy's container mixin. I made sure to add susy to the require array but it still doesn't like it when I include containers.

**Comment by mooror** [comment]
Heres my code btw 
appname.scss 
`$susy: (
  columns: 12,
  gutters: 1/4,
  math: fluid,
  output: float,
  gutter-position: inside,
);
//@import:'susy';
body{
    @include container(10%);
    background-color:green;
}`

**Comment by quaertym** [comment]
Did you try this? This should be placed in your Brocfile.
```
var app = new EmberApp({
  compassOptions: {
    require: ['susy']
  }
});
```

**Comment by mooror** [comment]
Yes I had tried this but unfortunately it did not work for me. Are those the only two steps? Updating the Brocfile and placing the code in the .scss file?

**Comment by quaertym** [comment]
Can you provide a sample repo that demonstrates so that I can investigate? I wonder if it is windows specific.
