### ISSUE TITLE
Adding to compass' sass-dir

### ISSUE THREAD

**Issue by fullofcaffeine** [quaertym/ember-cli-compass-compiler#51]
Hi!

I migrated from `ember-cli-sass` to `ember-cli-compass-compiler` because I needed to use a couple of compass mixins. I'm having an issue with paths, now. I have the following dir. structure:

```
├── Gemfile
├── Gemfile.lock
├── README.md
├── app
├── bower.json
├── bower_components
├── config
├── dist
├── ember-cli-build.js
├── node_modules
├── package.json
├── public
├── testem.json
├── tests
├── tmp
└── vendor
```

I have some `sass` files under vendor (i.e `vendor/select2/select2.sass`) that I used to just import directly from `styles/app.sass`, like this:

```
@import 'vendor/select2/select2'
@import 'vendor/select2/select2-bootstrap'
```

It worked great with `ember-cli-sass`, but breaks with `ember-cli-compass-compiler`/`compass`:

```
directory tmp/compass_compiler-tmp_cache_dir-98wbHwsq.tmp/assets
    error app/styles/app.sass (Line 3: File to import not found or unreadable: ../../vendor/select2/select2.
```

Now, I'm pretty sure this is related to the compass `--sass-dir` CLI command/option. Right now it's assumed to be `app/styles`. One possibility is to just move the `sass` stylesheets from vendor to a folder under `app/styles`, but I'd rather add `vendor` to the path. Is there a way to do it?

Thanks!

**Comment by quaertym** [comment]
Use relative paths or `importPath` option. README has examples for doing that. Please reopen if the issue is not fixed.
