### ISSUE TITLE
.scss files don't re-compile with `ember server`

### ISSUE THREAD

**Issue by cbornhoft** [quaertym/ember-cli-compass-compiler#52]
Right now, the only way to re-compile compass files with ember-cli-compass-compiler seems to be to run the command `ember build`.

However they should automatically re-compile if an ember server is running and a sass file is changed.

**Comment by cbornhoft** [comment]
It looks like it is actually auto-compiling, but at odd intervals. Sometimes it takes a good minute to realize a file has changed, whereas javascript files are instant.

**Comment by quaertym** [comment]
compass is slow compared to javascript compilation.

**Comment by cbornhoft** [comment]
@quaertym Cheers, I'm just surprised at how much slower it is. Build process without Sass seems to be 1/10th of what it is with.
