### ISSUE TITLE
'ember-cli-sass-and-compass-compiler' should be the name for the repo

### ISSUE THREAD

**Issue by ankushdharkar** [quaertym/ember-cli-compass-compiler#58]
I think it will be a good idea to rename the repo to **ember-cli-sass-and-compass-compiler**, since it's the complete solution of Sass + Compass, not just compass. I initially didn't want to use this because I thought it was compass only, and I still needed to find a way for Sass. But then I read the note, and now I am using it.

Take a look at what I did to the readme with a fork here :  https://github.com/ankushdharkar/ember-cli-sass-and-compass-compiler

**Comment by quaertym** [comment]
There is no need to refer `sass` explicitly since `compass` already implies it. This [SO answer] (http://stackoverflow.com/questions/13777215/what-is-compass-what-is-sass-how-do-they-differ) explains it beautifully:
> Quote from Sass and Compass in Action:
> Compass helps Sass authors write smarter stylesheets and empowers a community of designers and developers to create and share powerful frameworks. Put simply, Compass is a Sass framework, designed to make the work of styling the web smooth and efficient. Much like Rails as a web application framework for Ruby, Compass is a collection of helpful tools and battle-tested best practices for Sass.

[Compass website](http://compass-style.org/) also says on the homepage that `Compass uses Sass`.

I think we can expect people using compass to know that compass uses sass.

**Comment by ankushdharkar** [comment]
I think Rails need RVM installed before itself. Does it have its **own** compiler which is backward compatible and runs Ruby programs?

I guess you are right though.

**Comment by quaertym** [comment]
[README](https://github.com/quaertym/ember-cli-compass-compiler/blob/master/README.md) actually mentions that there is no need for additional sass libraries:
```
Note: This addon will compile your .scss files, in addition to making Compass's libraries available to your project. This means you do not need additional broccoli libraries for compiling sass, such as broccoli-sass.
```

RVM is Ruby Version Manager that helps you to maintain multiple versions of Ruby on the same machine. Rails does not require RVM but many people prefer RVM for its convenience. 

I think I did not get your question:
> Does it have its own compiler which is backward compatible and runs Ruby programs?
