### ISSUE TITLE
Default precision for compass is 5 -- need to increase it

### ISSUE THREAD

**Issue by gskaplan** [quaertym/ember-cli-compass-compiler#59]
I am using bootstrap sass with ember-cli-compass-compiler - button line-heights aren't working right because the default precision for compilation appears to be 5 digits, but I actually need 9. Specifically, the bootstrap sass defines base-line-height as 1.428571429 but it truncates it to 1.42857. This makes buttons mal-aligned.

How can I change the precision? I've scoured the Internet but nothing seems to solve this problem.

Thanks

**Comment by quaertym** [comment]
I think this issue belongs to the original [compass repo](https://github.com/Compass/compass).

**Comment by gskaplan** [comment]
Perhaps, however many of us who use ember-cli with Bootstrap are likely to encounter this problem and may circle back to this project since it is related to compass. I'll share my findings with you and you can elect if you want to reference this.

Compass is built on Ruby, and the way to override its operation is to provide a config.rb file in the project root that was generated by ember-cli. This is not intuitive since config.rb is a ruby file and with the exception of compass, there is nothing ruby in my project.

To override the default precision of compass, create the file named config.rb, and inside, place the following line:  Sass::Script::Number.precision = 10

The compass style compiler will find config.rb in your project root and use that precision when compiling scss files.
