### ISSUE TITLE
Latest broccoli-funnel causes files to go in the wrong directory

### ISSUE THREAD

**Issue by drewchandler** [quaertym/ember-cli-compass-compiler#60]
With the latest broccoli-funnel files are ending up in `assets/assets` rather than `assets`.

I've temporarily fixed this in my app by locking broccoli-funnel to `0.2.8` rather than `^0.2.8`.

**Comment by quaertym** [comment]
@drewchandler  Thanks for reporting this issue. It is fixed by `0.3.2` release.

**Comment by drewchandler** [comment]
Thanks so much for the quick fix!
