### ISSUE TITLE
CSS gets minified twice

### ISSUE THREAD

**Issue by drewchandler** [quaertym/ember-cli-compass-compiler#61]
My production builds we're having the CSS minified by both Compass and broccoli-clean-css. This resulted in CSS that was broken for some Android phone. My solution was to use `minifyCSS: { enabled: false }` in my `ember-cli-build.js` file.

I think we should either disable ember-cli's default minification, or document the need to disable it manually in the `README`.

**Comment by quaertym** [comment]
You can turn off minification for compass as well:
```
var app = new EmberApp({
  compassOptions: {
    outputStyle: 'expanded'
  }
});
```

**Comment by quaertym** [comment]
@drewchandler  Please submit a PR if README needs more clarification.
