### ISSUE TITLE
Compile separated files?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [quaertym/ember-cli-compass-compiler#62]
Hi, I want to know if is possible to have something like `app/styles/home.scss` and having it compiled to `dist/assets/home.css`, without having to import it explicitly in `app.scss`

**Comment by quaertym** [comment]
You should take a look at: http://www.ember-cli.com/user-guide/#configuring-output-paths

**Comment by IAmJulianAcosta** [comment]
Is normal to specify explicitly in `ember-cli-build.js` the files that I try to compile? 

```
Assets	                                       Output File
other CSS files in app/styles	same filename in /assets
``` 

I supposed that if I have a `scss` file in the `css` folder, it will compile automatically.

**Comment by quaertym** [comment]
This is the way to create app in `ember-cli-build.js`.
```js
var app = new EmberApp(defaults, {
  outputPaths: {
    app: {
      css: {
        'home': '/assets/home.css'
      }
    }
  }
});
```

**Comment by IAmJulianAcosta** [comment]
Thanks!
