### ISSUE TITLE
Wrong output filename on Windows

### ISSUE THREAD

**Issue by vlascik** [quaertym/ember-cli-compass-compiler#65]
0.3.2 doesn't really work on Windows (broccoli-funnel@1.0.0):
```javascript
			getDestinationPath: function (relativePath) {
				if (relativePath === path.join(this.destDir, fileName)) { return path.join(this.destDir, outputFileName); }
				return relativePath;
			}
```
relativePath gets "assets/app.css", while path.join(this.destDir, fileName) is "assets\app.css", equals test fails, and the final output filename is wrong (app.css), which breaks styling in the application, as the name should be my-app.css.

**Comment by quaertym** [comment]
I think it is better to fix it in broccoli-funnel. This issue seems related: https://github.com/broccolijs/broccoli-funnel/issues/53

**Comment by vlascik** [comment]
Thanks, you're probably right, I'll close it here.
