### ISSUE TITLE
compiler works on windows environment but not on mac

### ISSUE THREAD

**Issue by mmusket** [quaertym/ember-cli-compass-compiler#67]
I have an ember app that compiles scss files correctly on my windows environment but I am running into problems on OSX. 

When I run ember serve, I can see compass_compiler_output_path folders being created in the tmp folder, and the compiled css files are in there, 
but when I open the website I am greeted with a error 404 for file http://localhost:4200/assets/app.css

**Comment by quaertym** [comment]
I use this everyday on a mac. Compiled file has the name of your project. The correct link should be: http://localhost:4200/assets/<name-of-the-project>.css

**Comment by mmusket** [comment]
It was a while ago but I had changed the name of the main css file app.css. 
And never ran into problems until now. 
I'll try reference the app_name.css too just in case and report back

**Comment by mmusket** [comment]
So changing the file name to app_name.css works on macs. 
But I still have a problem cause on windows it only works if I reference app.css

**Comment by quaertym** [comment]
Please reopen with a repo that demonstrates the issue.
