### ISSUE TITLE
Error: File not found: /app/styles/app.scss

### ISSUE THREAD

**Issue by erzzo** [quaertym/ember-cli-compass-compiler#73]
Ember v: 2.7.0
Ember cli: 2.7.0

![image](https://cloud.githubusercontent.com/assets/886192/17272477/6c3b9628-5697-11e6-9217-f66a4ce577b2.png)

**Comment by quaertym** [comment]
Do you have a `app.scss` not `app.css` file under `app/styles`?

**Comment by erzzo** [comment]
It's there. I have sass installed https://github.com/aexmachina/ember-cli-sass and it is working without the compass compiler

**Comment by quaertym** [comment]
You need to remove other sass addons, `ember-cli-compass-compiler` does not depend on other addons.

**Comment by erzzo** [comment]
yes it's working now. But is it normal the compilation takes about 6s?

**Comment by erzzo** [comment]
I see now, it is here https://github.com/quaertym/ember-cli-compass-compiler/issues/70
