### ISSUE TITLE
Not finding any sass files

### ISSUE THREAD

**Issue by rijensky** [quaertym/ember-cli-compass-compiler#76]
Thank you for this plugin!

I'm working on windows with ember cli 2.11.1
Your docs are outdated and don't cover newer versions of ember-cli.

Creating an addon/styles dir does not work on the newer ember-cli versions, and they don't even have an index.js file anymore.
After a whole day bashing my head against this, I found a solution:
Here's the relevant part of my ember-cli-build.js:

```
var EmberApp = require('ember-cli/lib/broccoli/ember-app')
var production = EmberApp.env() === 'production';
var basePath = process.cwd().replace(/\\/g,"/") + "/";
var sassDir = basePath  + "app/styles";

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    compassOptions: {
      outputStyle: production ? 'compressed' : 'expanded',
      getSassDir: () => sassDir
    }
  });
  return app.toTree();
};
```

Should work on any os and with any version of ember-cli.
It's a bit of a hack, but it works like a charm.

Hope this helps someone. :)

**Comment by MrChriZ** [comment]
Out of curisoity why did you close this?
I found it useful!

**Comment by rijensky** [comment]
I don't really remember. I think I reinstalled everything and it worked.
